development:
  adapter: postgresql
  database: health_dashboard_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: health_dashboard_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: health_dashboard_production
  pool: 5
  timeout: 5000