default: &default
   adapter: postgresql
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   timeout: 5000

development:
  <<: *default
  database: my_database_development

docker:
  <<: *default
  host: psql-container
  database: health-dashboard
  username: health-user
  password: health-password

rspec:
  <<: *default
  host: psql-container
  database: health-dashboard-test
  username: health-user
  password: health-password

docker-compose:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV["POSTGRES_DB"] %>

test:
  <<: *default
  database: my_database_test

production:
  <<: *default
  database: my_database_production
